'use strict';
var React = require('react');
var Request = require('superagent');

module.exports = React.createClass({
	getInitialState: function() {
      return {
        locked: true
      }
    },

	propTypes: {
		className: React.default.PropTypes.string,
    	onChange: React.default.PropTypes.func,
    	value: React.default.PropTypes.string
    },

	render: function() {
		if (this.state.locked) {
			return <div className="input-group">
              <input className="form-control" disabled="disabled" type="text" data-key="Meta.Invoiceid" onChange={that.handleChange} value={inv.Meta.Invoiceid} placeholder="AUTOGENERATED"/>
              <div className="input-group-addon"><a onClick={this.toggleLock}><i className="fa fa-lock"></i></a></div>
	        </div>;
	    }

	    return <div className="input-group">
          <input className="form-control" type="text" data-key="Meta.Invoiceid" onChange={that.handleChange} value={inv.Meta.Invoiceid} placeholder="AUTOGENERATED"/>
          <div className="input-group-addon"><a onClick={this.toggleLock}><i className="fa fa-lock"></i></a></div>
        </div>;
	}
});