'use strict';
var React = require('react');
var Request = require('superagent');
require('./invoice.css');

module.exports = React.createClass({
  getInitialState: function() {
      return {
        company: "RootDev",
        entity: {
          name: "M.P. Droog",
          street1: "Dorpsstraat 236a",
          street2: "Obdam, 1713HP, NL"
        },
        customer: {
          name: "XSNews B.V.",
          street1: "New Yorkstraat 9-13",
          street2: "1175 RD Lijnden"
        },
        meta: {
          invoiceid: "",
          issuedate: "issuedate",
          ponumber: "P/O",
          duedate: "due"
        },
        lines: [{
          description: "description",
          quantity: 1,
          price: "12.00",
          total: "12.00"
        }],
        notes: "",
        total: {
          ex: "200",
          tax: "1000",
          total: "1200"
        },
        bank: {
          vat: "VAT",
          coc: "COC",
          iban: "IBEN"
        }
      };
  },

  componentDidMount: function() {
      this.ajax();
  },
  componentWillUnmount: function() {
  },

  ajax: function(range) {
  },

  updateField: function() {
    // TODO
  },

  lineAdd: function() {
    console.log("Add invoice line");
    this.state.lines.push({
      description: "",
      quantity: "1",
      price: "0.00",
      total: "0.00"
    });
    this.setState({lines: this.state.lines});
  },
  lineRemove: function(key) {
    if (confirm("Are you sure you want to remove the invoiceline with description '" + this.state.lines[key].description + "'?")) {
      console.log("Remove invoice line with key=" + key);
      console.log("Deleted idx ", this.state.lines.splice(key, 1)[0]);
      this.setState({lines: this.state.lines});
    }
  },

	render: function() {
    var inv = this.state;
    var that = this;
    var lines = [];

    inv.lines.forEach(function(line, idx) {
      lines.push(
        <tr key={"line"+idx}>
          <td><a onClick={that.lineRemove.bind(this, idx)}><i className="fa fa-trash"></i></a></td>
          <td><input className="form-control" type="text" value={line.description}/></td>
          <td><input className="form-control" type="text" value={line.quantity}/></td>
          <td><input className="form-control" type="text" value={line.price}/></td>
          <td><input className="form-control" disabled="disabled" type="text" value={line.total}/></td>
        </tr>
      );
    });

		return <form><div className="normalheader">
		    <div className="hpanel hblue">
          <div className="panel-heading hbuilt">
            <div className="panel-tools">
              <a href="#"><i className="fa fa-floppy-o"></i> Save</a>
              <a href="#"><i className="fa fa-close"></i> Discard</a>
              <a href="#"><i className="fa fa-lock"></i> Finalize</a>
            </div>
            New Invoice
          </div>
          <div className="panel-body">

<div className="invoice group">
  <div className="row">
    <div className="company col-sm-4">
      <input className="form-control" type="text" value={inv.company}/>
    </div>

    <div className="col-sm-offset-3 col-sm-1">
      From
    </div>
    <div className="entity col-sm-4">
      <input className="form-control" type="text" value={inv.entity.name}/>
      <input className="form-control" type="text" value={inv.entity.street1}/>
      <input className="form-control" type="text" value={inv.entity.street2}/>
    </div>
  </div>

  <div className="row">
    <div className="col-sm-1">
      Invoice For
    </div>
    <div className="col-sm-3">
      <input className="form-control" type="text" value={inv.customer.name}/>
      <input className="form-control" type="text" value={inv.entity.street1}/>
      <input className="form-control" type="text" value={inv.entity.street2}/>
    </div>
    <div className="meta col-sm-offset-3 col-sm-5">
      <table className="table">
        <tr>
          <td className="text">Invoice ID</td>
          <td><input className="form-control" disabled="disabled" type="text" value="AUTOGENERATED"/></td>
        </tr>
        <tr>
          <td className="text">Issue Date</td>
          <td><input className="form-control" type="text" value={inv.meta.issuedate}/></td>
        </tr>
        <tr>
          <td className="text">PO Number</td>
          <td><input className="form-control" type="text" value={inv.meta.ponumber}/></td>
        </tr>
        <tr>
          <td className="text">Due Date</td>
          <td><input className="form-control" type="text" value={inv.meta.duedate}/></td>
        </tr>
      </table>
    </div>
  </div>

  <table className="table table-striped">
    <thead>
      <tr>
        <th>&nbsp;</th>
        <th>Description</th>
        <th>Quantity</th>
        <th>Price</th>
        <th>Line Total</th>
      </tr>
    </thead>
    <tbody>{lines}</tbody>
    <tfoot>
      <tr>
        <td colSpan="3" className="text">
          <a onClick={this.lineAdd}><i className="fa fa-plus"></i> Add row</a>
        </td>
        <td className="text">Total (ex tax)</td>
        <td><input className="form-control" disabled="disabled" type="text" value={inv.total.ex}/></td>
      </tr>
      <tr>
        <td colSpan="3"></td>
        <td className="text">Tax (21%)</td>
        <td><input className="form-control" disabled="disabled" type="text" value={inv.total.tax}/></td>
      </tr>
      <tr>
        <td colSpan="3">&nbsp;</td>
        <td className="text">Total</td>
        <td><input className="form-control" disabled="disabled" type="text" value={inv.total.total}/></td>
      </tr>
    </tfoot>
  </table>

  <div className="row notes col-sm-12">
    <p>Notes</p>
    <textarea className="form-control" value={inv.notes}/>
  </div>
  <div className="row banking">
    <div className="col-sm-4">
      <p>Banking details</p>
      <table className="table">
        <tr><td className="text">VAT</td><td><input className="form-control" type="text" value={inv.bank.vat}/></td></tr>
        <tr><td className="text">CoC</td><td><input className="form-control" type="text" value={inv.bank.coc}/></td></tr>
        <tr><td className="text">IBAN</td><td><input className="form-control" type="text" value={inv.bank.iban}/></td></tr>
      </table>
    </div>
  </div>
</div>


	        </div>
		    </div>
    </div></form>;
	}
});
