// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/54b446166e62553ad923a42f8c6ec42f13cac69f/react-datepicker/react-datepicker.d.ts
declare module "react-datepicker" {
    interface ReactDatePicker {
        className?: string;
        dateFormat?: string;
        dateFormatCalendar?: string;
        disabled?: boolean;
        endDate?: {};
        excludeDates?: any[];
        filterDate?():any;
        id?: string;
        includeDates?: any[];
        isClearable?: boolean;
        locale?: string;
        maxDate?: {};
        minDate?: {};
        name?: string;
        onBlur?():any;
        onChange():any;
        onChange(date?:any):any;
        onFocus?():any;
        placeholderText?: string;
        popoverAttachment?: string;
        popoverTargetAttachment?: string;
        popoverTargetOffset?: string;
        readOnly?: boolean;
        renderCalendarTo?: any;
        required?: boolean;
        selected?: {};
        showYearDropdown?: boolean;
        startDate?: {};
        tabIndex?: number;
        tetherConstraints?: any[];
        title?: string;
        todayButton?: string;
        fixedHeight?: boolean;
    }
    let ReactDatePicker: __React.ClassicComponentClass<ReactDatePicker>;
    export = ReactDatePicker;
}
