// Code generated by tygo. DO NOT EDIT.

//////////
// source: crud.go

/**
 * DebtorItem wraps a debtor with its key for API responses.
 */
export interface DebtorItem {
  key: string;
  debtor: Debtor;
  lastInvoice?: string; // Last invoice date (YYYY-MM-DD)
}
/**
 * ProjectItem wraps a project with its key for API responses.
 */
export interface ProjectItem {
  key: string;
  project: Project;
}

//////////
// source: debtors.go
/*
Package entities manages company, user, and debtor data.
*/

/**
 * Debtor represents a customer or billing entity.
 */
export interface Debtor {
  Name: string;
  Street1: string;
  Street2: string;
  VAT: string;
  COC: string;
  TAX: string; // TODO: validate?
  NoteAdd: string;
  BillingEmail: string[];
  AccountingCode: string; // Relation code for accounting software export
}

//////////
// source: projects.go

/**
 * Project represents a billing project configuration.
 */
export interface Project {
  Name: string;
  Debtor: string;
  BillingEmail: string[];
  NoteAdd: string;
  HourRate: number /* float64 */;
  DueDays: number /* int */;
  PO: string;
  Street1: string;
}
