// Code generated by tygo. DO NOT EDIT.

//////////
// source: git.go
/*
Package git provides API endpoints for git status and push operations.
*/

/**
 * CommitInfo contains details about a single Git commit.
 */
export interface CommitInfo {
  hash: string;
  message: string;
  author: string;
  date: string;
}
/**
 * StatusResponse contains unpushed commit information.
 */
export interface StatusResponse {
  ahead: number /* int */;
  commits: CommitInfo[];
  remote: string;
}
/**
 * HistoryResponse contains paginated commit history.
 */
export interface HistoryResponse {
  commits: CommitInfo[];
  hasMore: boolean;
  page: number /* int */;
}
/**
 * PullPushResponse contains the result of a pull or push operation.
 */
export interface PullPushResponse {
  success: boolean;
  message: string;
}
/**
 * FileDiff contains diff information for a single file.
 */
export interface FileDiff {
  name: string;
  additions: number /* int */;
  deletions: number /* int */;
  patch: string;
}
/**
 * DiffResponse contains the diff for a specific commit.
 */
export interface DiffResponse {
  hash: string;
  message: string;
  author: string;
  date: string;
  files: FileDiff[];
}
