// Code generated by tygo. DO NOT EDIT.

//////////
// source: auth.go

export interface Sess {
  Email: string;
  Created: number /* int64 */;
  Version: number /* int */;
}
export interface Entities {
  Version: number /* int */;
  Company: { [key: string]: Entity};
  User: User[];
}
export interface Entity {
  Years: string[];
  YearRevenue: { [key: string]: string}; // Revenue per year (EUR)
  Name: string;
  COC: string;
  VAT: string;
  IBAN: string;
  BIC: string;
}
export interface User {
  Email: string;
  Company: string[];
  Name: string;
  Address1: string;
  Address2: string;
}
