// Code generated by tygo. DO NOT EDIT.

//////////
// source: auth.go

/**
 * SessionMaxAge is the maximum age of a session in seconds (8 hours)
 */
export const SessionMaxAge = 8 * 60 * 60;
/**
 * IVSize is the size of random bytes to generate (24 bytes = 32 base64 chars)
 */
export const IVSize = 24;
export interface Sess {
  Email: string;
  Created: number /* int64 */;
  Version: number /* int */;
}
export interface Entities {
  Version: number /* int */;
  Company: { [key: string]: Entity};
  User: User[];
}
export interface Entity {
  Years: string[];
  YearRevenue: { [key: string]: string}; // Revenue per year (EUR)
  Name: string;
  COC: string;
  VAT: string;
  IBAN: string;
  BIC: string;
}
export interface User {
  Email: string;
  Company: string[];
  Name: string;
  Address1: string;
  Address2: string;
}
