// Code generated by tygo. DO NOT EDIT.

//////////
// source: dashboard.go
/*
Package model defines shared data structures for invoices, hours, and taxes.
*/

/**
 * TaxSummary contains aggregated tax data for a quarter
 */
export interface TaxSummary {
  Ex: string; // Sum revenue of NL invoices
  Tax: string; // Tax to pay
  EUEx: string; // Sum revenue of EU invoices
  EUCompany: { [key: string]: string }; // Revenue per EU company VAT number (for ICP)
  ExWorld: string; // Sum revenue of world invoices
  ExRevenue: string; // Sum revenue of everything
}
/**
 * InvoiceAuditLine contains info for audit logging
 */
export interface InvoiceAuditLine {
  InvoiceID: string;
  TaxCategory: string;
  TotalEx: string;
  TotalTax: string;
}
/**
 * CustomerTotal represents revenue per customer
 */
export interface CustomerTotal {
  Name: string;
  Revenue: string;
  InvoiceCount: number /* int */;
}
/**
 * QuarterSummary contains aggregated data for a quarter
 */
export interface QuarterSummary {
  Quarter: number /* int */;
  InvoiceCount: number /* int */;
  TotalRevenue: string;
  TotalTax: string;
  PaidCount: number /* int */;
  UnpaidCount: number /* int */;
  PaidRevenue: string;
  UnpaidRevenue: string;
}
/**
 * MonthlyMetric contains revenue and hours for a month
 */
export interface MonthlyMetric {
  RevenueTotal: string;
  RevenueEx: string;
  Hours: string;
}
/**
 * UnpaidSummary contains summary of unpaid invoices
 */
export interface UnpaidSummary {
  Count: number /* int */;
  TotalAmount: string;
}
/**
 * OverdueInvoice represents an overdue invoice
 */
export interface OverdueInvoice {
  ID: string;
  InvoiceID: string;
  CustomerName: string;
  DueDate: string;
  Amount: string;
  DaysOverdue: number /* int */;
  Quarter: number /* int */;
}
/**
 * UnbilledHoursSummary contains summary of unbilled hours
 */
export interface UnbilledHoursSummary {
  Count: number /* int */;
  TotalHours: string;
}
/**
 * YearComparison contains comparison between two years
 */
export interface YearComparison {
  CurrentYear: number /* int */;
  PreviousYear: number /* int */;
  CurrentRevenue: string;
  PreviousRevenue: string;
  GrowthPercent: string;
  GrowthAmount: string;
}
/**
 * DashboardMetric is used by the simple dashboard endpoint
 */
export interface DashboardMetric {
  RevenueTotal: string;
  RevenueEx: string;
  Hours: string;
}
/**
 * DashboardResponse contains all dashboard data for the API
 */
export interface DashboardResponse {
  monthly: { [key: string]: MonthlyMetric | undefined };
  monthlyPrevYear: { [key: string]: MonthlyMetric | undefined };
  unpaid: UnpaidSummary;
  overdue: OverdueInvoice[];
  quarters: QuarterSummary[];
  unbilledHours: UnbilledHoursSummary;
  yearComparison: YearComparison;
  topClients: CustomerTotal[];
}
/**
 * AccountingInvoice contains invoice data for accounting export
 */
export interface AccountingInvoice {
  InvoiceID: string;
  Issuedate: string;
  CustomerName: string;
  CustomerVAT: string;
  TaxCategory: string; // NL, EU0, WORLD0
  Status: string; // PAID, UNPAID
  Quarter: number /* int */;
  TotalEx: number /* float64 */;
  TotalTax: number /* float64 */;
  TotalInc: number /* float64 */;
  AccountingCode: string; // From debtor record
}
/**
 * AccountingCompany contains company totals for accounting export
 */
export interface AccountingCompany {
  Name: string;
  VAT: string;
  TaxCategory: string; // NL, EU0, WORLD0
  TotalRevenue: number /* float64 */;
  AccountingCode: string;
}
/**
 * AccountingExport contains all data for the accounting Excel export
 */
export interface AccountingExport {
  Invoices: AccountingInvoice[];
  Companies: AccountingCompany[];
  TotalRevenue: number /* float64 */;
  TotalEx: number /* float64 */;
  TotalTax: number /* float64 */;
  TotalHours: number /* float64 */;
}

//////////
// source: hour.go

/**
 * HourLine represents a single time entry for hour tracking.
 */
export interface HourLine {
  Day: string;
  Start: string;
  Stop: string;
  Hours: number /* float64 */;
  Description: string;
}
/**
 * Hour represents a collection of hour entries for a project.
 */
export interface Hour {
  Project: string;
  Name: string;
  Status: string;
  Total: string;
  HourRate: number /* float64 */; // cache
  Issuedate: string; // YYYY-MM-DD, derived from filename if not set
  Lines: HourLine[];
}

//////////
// source: invoice.go

/**
 * InvoiceMail contains email settings for an invoice.
 */
export interface InvoiceMail {
  From: string;
  Subject: string;
  To: string;
  Body: string;
}
/**
 * InvoiceEntity contains the seller/entity details.
 */
export interface InvoiceEntity {
  Name: string;
  Street1: string;
  Street2: string;
}
/**
 * InvoiceCustomer contains the buyer/customer details.
 */
export interface InvoiceCustomer {
  Name: string;
  Street1: string;
  Street2: string;
  Vat: string;
  Coc: string;
  Tax: string; // Simple string so we know what to tax
}
/**
 * InvoiceMeta contains invoice metadata like dates and IDs.
 */
export interface InvoiceMeta {
  Conceptid: string;
  Status: string;
  Invoiceid: string;
  Issuedate: string;
  Ponumber: string;
  Duedate: string;
  Paydate: string;
  Freefield: string;
  HourFile: string;
}
/**
 * InvoiceLine represents a single line item on an invoice.
 */
export interface InvoiceLine {
  Description: string;
  Quantity: string;
  Price: string;
  Total: string;
}
/**
 * InvoiceTotal contains the invoice totals.
 */
export interface InvoiceTotal {
  Ex: string;
  Tax: string;
  Total: string;
}
/**
 * InvoiceBank contains banking details for payment.
 */
export interface InvoiceBank {
  Vat: string;
  Coc: string;
  Iban: string;
  Bic: string;
}
/**
 * Invoice represents a complete invoice document.
 */
export interface Invoice {
  Company: string;
  Entity: InvoiceEntity;
  Customer: InvoiceCustomer;
  Meta: InvoiceMeta;
  Lines: InvoiceLine[];
  Notes: string;
  Total: InvoiceTotal;
  Bank: InvoiceBank;
  Mail: InvoiceMail;
}
