// Code generated by tygo. DO NOT EDIT.

//////////
// source: dashboard.go

/**
 * TaxSummary contains aggregated tax data for a quarter
 */
export interface TaxSummary {
  Ex: string; // Sum revenue of NL invoices
  Tax: string; // Tax to pay
  EUEx: string; // Sum revenue of EU invoices
  EUCompany: { [key: string]: string}; // Revenue per EU company VAT number (for ICP)
  ExWorld: string; // Sum revenue of world invoices
  ExRevenue: string; // Sum revenue of everything
}
/**
 * InvoiceAuditLine contains info for audit logging
 */
export interface InvoiceAuditLine {
  InvoiceID: string;
  TaxCategory: string;
  TotalEx: string;
  TotalTax: string;
}
/**
 * CustomerTotal represents revenue per customer
 */
export interface CustomerTotal {
  Name: string;
  Revenue: string;
  InvoiceCount: number /* int */;
}
/**
 * QuarterSummary contains aggregated data for a quarter
 */
export interface QuarterSummary {
  Quarter: number /* int */;
  InvoiceCount: number /* int */;
  TotalRevenue: string;
  TotalTax: string;
  PaidCount: number /* int */;
  UnpaidCount: number /* int */;
  PaidRevenue: string;
  UnpaidRevenue: string;
}
/**
 * MonthlyMetric contains revenue and hours for a month
 */
export interface MonthlyMetric {
  RevenueTotal: string;
  RevenueEx: string;
  Hours: string;
}
/**
 * UnpaidSummary contains summary of unpaid invoices
 */
export interface UnpaidSummary {
  Count: number /* int */;
  TotalAmount: string;
}
/**
 * OverdueInvoice represents an overdue invoice
 */
export interface OverdueInvoice {
  ID: string;
  InvoiceID: string;
  CustomerName: string;
  DueDate: string;
  Amount: string;
  DaysOverdue: number /* int */;
  Quarter: number /* int */;
}
/**
 * UnbilledHoursSummary contains summary of unbilled hours
 */
export interface UnbilledHoursSummary {
  Count: number /* int */;
  TotalHours: string;
}
/**
 * YearComparison contains comparison between two years
 */
export interface YearComparison {
  CurrentYear: number /* int */;
  PreviousYear: number /* int */;
  CurrentRevenue: string;
  PreviousRevenue: string;
  GrowthPercent: string;
  GrowthAmount: string;
}
/**
 * DashboardMetric is used by the simple dashboard endpoint
 */
export interface DashboardMetric {
  RevenueTotal: string;
  RevenueEx: string;
  Hours: string;
}
/**
 * DashboardResponse contains all dashboard data for the API
 */
export interface DashboardResponse {
  monthly: { [key: string]: MonthlyMetric | undefined};
  monthlyPrevYear: { [key: string]: MonthlyMetric | undefined};
  unpaid: UnpaidSummary;
  overdue: OverdueInvoice[];
  quarters: QuarterSummary[];
  unbilledHours: UnbilledHoursSummary;
  yearComparison: YearComparison;
  topClients: CustomerTotal[];
}

//////////
// source: hour.go

export interface HourLine {
  Day: string;
  Start: string;
  Stop: string;
  Hours: number /* float64 */;
  Description: string;
}
export interface Hour {
  Project: string;
  Name: string;
  Status: string;
  Total: string;
  HourRate: number /* float64 */; // cache
  Issuedate: string; // YYYY-MM-DD, derived from filename if not set
  Lines: HourLine[];
}

//////////
// source: invoice.go

export interface InvoiceMail {
  From: string;
  Subject: string;
  To: string;
  Body: string;
}
export interface InvoiceEntity {
  Name: string;
  Street1: string;
  Street2: string;
}
export interface InvoiceCustomer {
  Name: string;
  Street1: string;
  Street2: string;
  Vat: string;
  Coc: string;
  Tax: string; // Simple string so we know what to tax
}
export interface InvoiceMeta {
  Conceptid: string;
  Status: string;
  Invoiceid: string;
  Issuedate: string;
  Ponumber: string;
  Duedate: string;
  Paydate: string;
  Freefield: string;
  HourFile: string;
}
export interface InvoiceLine {
  Description: string;
  Quantity: string;
  Price: string;
  Total: string;
}
export interface InvoiceTotal {
  Ex: string;
  Tax: string;
  Total: string;
}
export interface InvoiceBank {
  Vat: string;
  Coc: string;
  Iban: string;
  Bic: string;
}
export interface Invoice {
  Company: string;
  Entity: InvoiceEntity;
  Customer: InvoiceCustomer;
  Meta: InvoiceMeta;
  Lines: InvoiceLine[];
  Notes: string;
  Total: InvoiceTotal;
  Bank: InvoiceBank;
  Mail: InvoiceMail;
}
