// Code generated by tygo. DO NOT EDIT.

//////////
// source: struct.go

/**
 * PurchaseInvoice represents an incoming invoice from a supplier
 */
export interface PurchaseInvoice {
  ID: string; // Original invoice ID from supplier
  Supplier: Supplier;
  Issuedate: string;
  Duedate: string;
  TotalEx: string;
  TotalTax: string;
  TotalInc: string;
  Currency: string;
  PaymentRef: string; // Payment reference (e.g. RF number)
  IBAN: string;
  BIC: string;
  Lines: PurchaseLine[];
  PDFFilename: string; // Embedded PDF filename
  XMLFilename: string; // Original XML filename
  Status: string; // UNPAID, PAID
  Paydate: string;
}
export interface Supplier {
  Name: string;
  VAT: string;
  COC: string;
  Email: string;
}
export interface PurchaseLine {
  Description: string;
  Quantity: string;
  Price: string;
  Total: string;
  TaxPercent: string;
}
export interface ListReply {
  Invoices: { [key: string]: (PurchaseInvoice | undefined)[]};
}
